version: 2
updates:
- package-ecosystem: pip
  directory: "/modules/python"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: awscli
    versions:
    - 1.18.222
    - 1.18.223
    - 1.19.1
    - 1.19.10
    - 1.19.11
    - 1.19.12
    - 1.19.13
    - 1.19.14
    - 1.19.15
    - 1.19.16
    - 1.19.17
    - 1.19.18
    - 1.19.19
    - 1.19.20
    - 1.19.21
    - 1.19.23
    - 1.19.24
    - 1.19.26
    - 1.19.27
    - 1.19.28
    - 1.19.29
    - 1.19.3
    - 1.19.31
    - 1.19.33
    - 1.19.34
    - 1.19.35
    - 1.19.36
    - 1.19.37
    - 1.19.39
    - 1.19.4
    - 1.19.40
    - 1.19.41
    - 1.19.42
    - 1.19.43
    - 1.19.44
    - 1.19.45
    - 1.19.46
    - 1.19.47
    - 1.19.49
    - 1.19.5
    - 1.19.50
    - 1.19.51
    - 1.19.53
    - 1.19.54
    - 1.19.55
    - 1.19.56
    - 1.19.57
    - 1.19.59
    - 1.19.6
    - 1.19.7
    - 1.19.8
    - 1.19.9
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
    - 21.4b1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: pytest-mypy
    versions:
    - 0.8.0
