
TERRAFORM_CONFIG_FOLDER ?= .


terraform/linter: $(TERRAFORM_BINARY) ## Lint the terraform recipe
	@echo -e "\e[32m==> Lint terraform \e[0m"
	@cd $(TERRAFORM_CONFIG_FOLDER) && \
	 $(TERRAFORM_BINARY) init --backend=false && \
	 $(TERRAFORM_BINARY) validate .
