
TERRAFORM_CONFIG_FOLDER ?= .


terraform/format-code: $(TERRAFORM_BINARY) ## Format the terraform recipe
	@echo -e "\e[32m==> Format terraform code from folder $(TERRAFORM_CONFIG_FOLDER) \e[0m"
	@cd $(TERRAFORM_CONFIG_FOLDER) && \
	 $(TERRAFORM_BINARY) init --backend=false && \
	 $(TERRAFORM_BINARY) fmt