include $(BUILD_HARNESS_PATH)/modules/terraform/Makefile.terraform
include $(BUILD_HARNESS_PATH)/modules/python/lambda/Makefile.lambda

TERRAFORM_CONFIG_FOLDER ?= .
# this is a terraform work around with the aws provider. if this is not set it would error.
# https://github.com/hashicorp/terraform/issues/21408
export AWS_DEFAULT_REGION = us-east-1

$(RESULTS_TERRAFORM_TEST_PATH_XML): $(TERRAFORM_BINARY)

terraform/test: $(RESULTS_TERRAFORM_TEST_PATH_XML) ## Test terraform module
	@echo -e "\e[32m==> test terraform module \e[0m"
	@echo $(RESULTS_TERRAFORM_TEST_PATH_XML)

