
TERRAFORM_CONFIG_FOLDER ?= .


terraform/init: $(TERRAFORM_BINARY) ## init terraform recipe
	@echo -e "\e[32m==> Init terraform \e[0m"
	@cd $(TERRAFORM_CONFIG_FOLDER) && \
	 $(TERRAFORM_BINARY) init -input=false
