

$(LAMBDA_PACKAGES_ZIPS_PUBLISHED): $(TERRAFORM_LAMBDA_PACKAGES_PATH)/%.$(VERSION).published : $(TERRAFORM_LAMBDA_PACKAGES_PATH)/%.$(VERSION).zip $(VIRTUAL_ENV_AWS_ACTIVATE)
	@echo -e "\e[32m==> Publish lambda packages $< to S3 $(S3_BUCKET_URL)/$*/$(VERSION)/package.zip \e[0m"
	@source $(VIRTUAL_ENV_AWS_ACTIVATE)  && aws s3 cp $< $(S3_BUCKET_URL)/$*/$(VERSION)/package.zip

aws/publish-lambda-packages-S3: $(LAMBDA_PACKAGES_ZIPS_PUBLISHED) ## Publish all the lambda packages to S3
	@echo -e "\e[32m==> Publish lambda packages to S3 \e[0m"